CREATE TABLE debt_reply (
id INT AUTO_INCREMENT PRIMARY KEY,
debt_reminder_id CHAR(10) NOT NULL ,
user_reply_id INT NOT NULL,
content VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deleted_at TIMESTAMP NULL DEFAULT NULL,
CONSTRAINT fk_debt_reminder_id FOREIGN KEY (debt_reminder_id) REFERENCES transactions(id) ON DELETE CASCADE
);