version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: vukhoa23/banking-be:local
    container_name: backend_container
    depends_on:
      - redis
      - mysql
    ports:
      - "8080:8080"
    restart: always  # Automatically restart the container if it stops

  frontend:
    image: qhuongng/wnc-banking-fe:local
    container_name: banking_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mysql_data:
