definitions:
  entity.Customer:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      phoneNumber:
        type: string
      updatedAt:
        type: string
    type: object
  httpcommon.Error:
    properties:
      code:
        type: string
      field:
        type: string
      message:
        type: string
    type: object
  httpcommon.HttpResponse-any:
    properties:
      data: {}
      errors:
        items:
          $ref: '#/definitions/httpcommon.Error'
        type: array
      success:
        type: boolean
    type: object
  httpcommon.HttpResponse-entity_Customer:
    properties:
      data:
        $ref: '#/definitions/entity.Customer'
      errors:
        items:
          $ref: '#/definitions/httpcommon.Error'
        type: array
      success:
        type: boolean
    type: object
  httpcommon.HttpResponse-int64:
    properties:
      data:
        type: integer
      errors:
        items:
          $ref: '#/definitions/httpcommon.Error'
        type: array
      success:
        type: boolean
    type: object
  httpcommon.HttpResponse-model_GetCustomerNameByAccountNumberResponse:
    properties:
      data:
        $ref: '#/definitions/model.GetCustomerNameByAccountNumberResponse'
      errors:
        items:
          $ref: '#/definitions/httpcommon.Error'
        type: array
      success:
        type: boolean
    type: object
  model.GetCustomerNameByAccountNumberResponse:
    properties:
      name:
        type: string
    type: object
  model.InternalTransferRequest:
    properties:
      amount:
        minimum: 0
        type: integer
      isSourceFee:
        type: boolean
      sourceAccountNumber:
        type: string
      targetAccountNumber:
        type: string
    required:
    - amount
    - isSourceFee
    - sourceAccountNumber
    - targetAccountNumber
    type: object
  model.LoginRequest:
    properties:
      email:
        maxLength: 255
        minLength: 10
        type: string
      password:
        maxLength: 255
        minLength: 8
        type: string
      recaptchaToken:
        type: string
    required:
    - email
    - password
    - recaptchaToken
    type: object
  model.RegisterRequest:
    properties:
      email:
        maxLength: 255
        minLength: 10
        type: string
      name:
        maxLength: 255
        minLength: 5
        type: string
      password:
        maxLength: 255
        minLength: 8
        type: string
      phoneNumber:
        maxLength: 255
        minLength: 10
        type: string
    required:
    - email
    - name
    - password
    - phoneNumber
    type: object
  model.SendOTPRequest:
    properties:
      email:
        maxLength: 255
        minLength: 10
        type: string
    required:
    - email
    type: object
  model.VerifyOTPRequest:
    properties:
      email:
        maxLength: 255
        minLength: 10
        type: string
      otp:
        maxLength: 6
        minLength: 6
        type: string
    required:
    - email
    - otp
    type: object
info:
  contact: {}
paths:
  /account/customer-name:
    get:
      description: Get Customer Name by Account Number
      parameters:
      - description: Account payload
        in: query
        name: accountNumber
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-model_GetCustomerNameByAccountNumberResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
      summary: Get Customer Name by Account Number
      tags:
      - Accounts
  /account/internal-transfer:
    post:
      consumes:
      - application/json
      description: Transfer from internal account to internal account
      parameters:
      - description: Account payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.InternalTransferRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
      summary: Transfer
      tags:
      - Accounts
  /auth/forgot-password/verify-otp:
    post:
      consumes:
      - application/json
      description: Verify OTP with email and otp
      parameters:
      - description: Verify OTP payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.VerifyOTPRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
      summary: Verify OTP
      tags:
      - Auths
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login to account
      parameters:
      - description: Auth payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-entity_Customer'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
      summary: Login
      tags:
      - Auths
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register to account
      parameters:
      - description: Auth payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
      summary: Register
      tags:
      - Auths
  /auth/reset-password/otp:
    post:
      consumes:
      - application/json
      description: Send OTP to user email
      parameters:
      - description: Send OTP payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SendOTPRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
      summary: Send OTP to Mail
      tags:
      - Auths
  /core/estimate-transfer-fee:
    get:
      consumes:
      - application/json
      description: Estimate the internal transfer fee
      parameters:
      - description: Amount to estimate
        in: query
        name: amount
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-int64'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
      summary: EstimateTransferFee
      tags:
      - Cores
swagger: "2.0"
