definitions:
  entity.Customer:
    properties:
      createdAt:
        type: string
      deleteddAt:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      phoneNumber:
        type: string
      updatedAt:
        type: string
    type: object
  httpcommon.Error:
    properties:
      code:
        type: string
      field:
        type: string
      message:
        type: string
    type: object
  httpcommon.HttpResponse-any:
    properties:
      data: {}
      errors:
        items:
          $ref: '#/definitions/httpcommon.Error'
        type: array
      success:
        type: boolean
    type: object
  httpcommon.HttpResponse-entity_Customer:
    properties:
      data:
        $ref: '#/definitions/entity.Customer'
      errors:
        items:
          $ref: '#/definitions/httpcommon.Error'
        type: array
      success:
        type: boolean
    type: object
  model.LoginRequest:
    properties:
      email:
        maxLength: 255
        minLength: 10
        type: string
      password:
        maxLength: 255
        minLength: 8
        type: string
      recaptchaToken:
        type: string
    required:
    - email
    - password
    - recaptchaToken
    type: object
  model.RegisterRequest:
    properties:
      email:
        maxLength: 255
        minLength: 10
        type: string
      password:
        maxLength: 255
        minLength: 8
        type: string
      phoneNumber:
        maxLength: 255
        minLength: 10
        type: string
    required:
    - email
    - password
    - phoneNumber
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login to account
      parameters:
      - description: Auth payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-entity_Customer'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
      summary: Login
      tags:
      - Auths
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register to account
      parameters:
      - description: Auth payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
      summary: Register
      tags:
      - Auths
swagger: "2.0"
